### PR TITLE
fix up xvfb-run command, currently it prompts errors and hangs

### PR DESCRIPTION
**Pull request by romandrahan**
Solving #1

### CODE REVIEW

**Comment by tyranron** [comment]
@romandragan can we make `xvfb-run` as `ENTRYPOINT` of image and `pub run test` as `CMD`?

**Comment by romandrahan** [comment]
@tyranron, we can't use `xvfb-run` and `pub run test` separately. But we can just combine them into one single command in CMD like `CMD xvfb-run -s '-screen 0 1024x768x24' -e /dev/stderr pub run test`.

In this case we can just use this image without additional `--entrypoint` and `-c` flags while testing, cause we already have required test-command running at startup.

**Comment by tyranron** [comment]
@romandragan there must be a way to combine stuff like I have described.

Tests are not the pain.

Why in such manner?  
Having `xvfb-run` hidden behind `ENTRYPOINT` simplifies common usage of the image so, that users of image do not have to mess with `xvfb-run` command. Just simple:
```
docker run --rm instrumentisto/dart-content-shell pub run test
# or
docker run --rm instrumentisto/dart-content-shell content_shell --dump-renderer-tree http://google.com
```
While having everything in `CMD` makes users to worry about `xvfb` part, that is the same in most cases.

**Comment by romandrahan** [comment]
@tyranron, now we can use image like:
```bash
docker run --rm instrumentisto/dart-content-shell "pub run test"
# or
docker run --rm instrumentisto/dart-content-shell "content_shell --dump-render-tree http://google.com"
```

**Note**, that quotes in the executing command are required.

Taken from https://github.com/damoti/content-shell/blob/master/Dockerfile

**Comment by tyranron** [comment]
@romandragan I think if we use `"$0"` instead `$0` we can get rid of those quotes.

**Comment by romandrahan** [comment]
>use "$0" instead $0

@tyranron, unfortunately we can't use it like that. In that case in the `$0` variable we'll have only `pub` part of the command. Then `run` will be in `$1` and `test` in `$2`.

That's why we need to provide whole `pub run test` command as one string using double `"` or single `'` quotes.

**Comment by tyranron** [comment]
@romandragan what about `"$@"` or `$@`?

**Comment by romandrahan** [comment]
@tyranron, found solution: `$0 $*`. As [described in reference](https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html) `$0` will contain first command (in our case `pub`), and `$*` will contain all rest parameters as glued string (in our case `run test`).

Then we can run image simply like that:
```bash
docker run --rm instrumentisto/dart-content-shell pub run test
# or
docker run --rm instrumentisto/dart-content-shell content_shell --dump-render-tree google.com
```

**Comment by tyranron** [comment]
@romandragan nice

**Review by tyranron — APPROVED** [review]

**Pull request merged**
